highlighter: pygments
markdown: redcarpet
port: 8080
url: "http://docs.hookscript.com"
exclude:
    - CNAME
    - Gemfile
    - Gemfile.lock
    - Makefile
    - README.md
    - lang
    - script
    - _includes/examples/README.md
gems:
    - jekyll-sitemap
